version: "3.8"

services:
  client:
    build: ./client
    ports:
      - 5173:5173
    volumes:
      - ./apps/client:/app
      # https://stackoverflow.com/a/37898591
      # exclude node_modules due to Vite error
      - /app/node_modules/
    environment:
      - API_URL=http://localhost:8081/

  server:
    build: ./server
    ports:
      - 8081:8081
    volumes:
      - ./apps/server:/app
    environment:
      - PORT=8081
